site_name: "Shark Tracking Graph Docs"
site_description: "API for tracking shark migration patterns using FastAPI and Neo4j"

theme:
  name: material
  language: pl

nav:
  - Home: index.md
  - API Reference: api.md
  - Database Architecture: database.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            paths: [.]
