[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shark-tracking-graph"
version = "0.1.0"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "neo4j>=5.18.0"
]

[tool.ruff]
# Target version of the Python runtime
target-version = "py312"
line-length = 120

[tool.ruff.lint]
# E (Error), F (Pyflakes), B (Bugbear), I (Isort)
select = ["E", "F", "B", "I"]
ignore = []

[tool.ruff.lint.isort]
# Global layout configuration for import sorting
known-first-party = ["src"]
